<?php
$health_centers_by_district = [
    'District 1' => [
        ['name' => 'District I – Health Office', 'contact' => '09662209857', 'email' => '', 'physician' => 'Dr. Clairrol M. Astilla, MO III, OIC', 'address' => 'San Francisco Super Health Center'],
        ['name' => 'Bago Bantay', 'contact' => '09331422533', 'email' => 'bagobantayhc.cityhealth@quezoncity.gov.ph', 'physician' => 'Dr. Stephanie Joshua G. Rivera', 'address' => '84 Sto. Niño St., Brgy. Alicia'],
        ['name' => 'Bagong Pag-asa', 'contact' => '09196667054', 'email' => 'bagongpagasahc.cityhealth@quezoncity.gov.ph', 'physician' => 'Dr. Ferdinand C. Cavalida', 'address' => '36 Road 9 cor. Road 10, Brgy. Bagong Pag-asa'],
        ['name' => 'Balingasa', 'contact' => '09161710747', 'email' => 'balingasahc.cityhealth@quezoncity.gov.ph', 'physician' => 'Dr. Romarie Jane M. Queddeng', 'address' => '26 J. Aquino Cruz St., Brgy. Balingasa'],
        ['name' => 'La Loma', 'contact' => '71210645', 'email' => 'lalomahc.cityhealth@quezoncity.gov.ph', 'physician' => 'Dr. Gavina Aurora F. David', 'address' => '225 Mariveles St., Brgy. Paang Bundok'],
        ['name' => 'Masambong', 'contact' => '09205246039', 'email' => 'masambonghc.cityhealth@quezoncity.gov.ph', 'physician' => 'Dr. Jose Maria F. Fernandez', 'address' => '8 Malac St., Brgy. Masambong'],
        ['name' => 'Paltok', 'contact' => '09175443411', 'email' => 'paltokhc.cityhealth@quezoncity.gov.ph', 'physician' => 'Dr. Jan Dominik C. Arceo', 'address' => '14 Matias St., Brgy. Paltok'],
        ['name' => 'Mercedes de Joya', 'contact' => '09328430155', 'email' => 'mdjhc.cityhealth@quezoncity.gov.ph', 'physician' => 'Dr. Joyse Nicole B. Denoga', 'address' => 'Dapitan cor. Mayon St., Brgy. Sta. Teresita'],
        ['name' => 'Project 6', 'contact' => '09178986815', 'email' => 'project6hc.cityhealth@quezoncity.gov.ph', 'physician' => 'Dr. Arnold E. Monteiro', 'address' => '58 Alley 3, Brgy. Project 6'],
        ['name' => 'Project 7', 'contact' => '09926826490', 'email' => 'project7hc.cityhealth@quezoncity.gov.ph', 'physician' => 'Dr. Kheizl Mae R. Bernardo', 'address' => '39 Bansalangin St., Brgy Veterans Village'],
        ['name' => 'San Antonio', 'contact' => '83748925', 'email' => 'sanantoniohc.cityhealth@quezoncity.gov.ph', 'physician' => 'Dr. Fharcy B. Bausa', 'address' => '38 San Jose, St. Brgy. San Antonio'],
        ['name' => 'San Francisco Super', 'contact' => '09183309157', 'email' => 'sanfranciscoshc.cityhealth@quezoncity.gov.ph', 'physician' => 'Dr. Mechael Angelo G. Marasigan / Dr. Kristine Joyce I. Dioso-Fabile', 'address' => 'H. Francisco cor. San Vicente St. Brgy Damayan'],
        ['name' => 'San Jose', 'contact' => '71481871', 'email' => 'sanjosehc.cityhealth@quezoncity.gov.ph', 'physician' => 'Dr. Keiko Sharlene C. Takahashi', 'address' => '27 Tinagan St., Brgy. San Jose'],
        ['name' => 'Toro Hills', 'contact' => '09228268799', 'email' => 'torohillshc.cityhealth@quezoncity.gov.ph', 'physician' => 'Dr. Shane D. Marte', 'address' => 'Road 11, Brgy. Bahay Toro'],
    ],
    'District 2' => [
        ['name' => 'District II – Health Office', 'contact' => '09228304110', 'email' => 'district2.cityhealth@quezoncity.gov.ph', 'physician' => 'Dr. Karen Gemma A. See, MO IV', 'address' => 'Batasan Hills Super Health Center'],
        ['name' => 'Bagong Silangan', 'contact' => '87131918/09778091108', 'email' => 'bagongsilanganhc.cityhealth@quezoncity.gov.ph', 'physician' => 'Dr. Michael Jonathan R. Palad/Dr. Karl Adrian Punzalan', 'address' => 'Bonifacio St., Brgy. Bagong Silangan'],
        ['name' => 'Batasan Hills Annex', 'contact' => '09669848229', 'email' => 'batasanhillshc.cityhealth@quezoncity.gov.ph', 'physician' => 'Dr. Rigelle Anne C. Delos Santos', 'address' => 'Bill cor. Saret St., Brgy. Batasan Hills'],
        ['name' => 'Batasan Hills Super', 'contact' => '09357919496', 'email' => 'batasanhillsshc.cityhealth@quezoncity.gov.ph', 'physician' => 'Dr. Ericka Joan R. Nera / Dr. Richa Maria Therese Angelica C. Lanuza', 'address' => '2 IBP Road, Brgy. Batasan Hills'],
        ['name' => 'Betty Go Belmonte Super', 'contact' => '71491340/09161693601', 'email' => 'bgbelmonteshc.cityhealth@quezoncity.gov.ph', 'physician' => 'Dr. Michelle G. Sanorjo-Aberin', 'address' => '2nd Flr. 12 Artillery Road, Brgy. Holy Spirit'],
        ['name' => 'Commonwealth', 'contact' => '09228793305/87116485', 'email' => 'commonwealthhc.cityhealth@quezoncity.gov.ph', 'physician' => 'Dr. Grace Lyn C. Maestro', 'address' => 'Katuparan St., Brgy. Commonwealth'],
        ['name' => 'Doña Nicasia', 'contact' => '09665692138/86951161', 'email' => 'donanicasiahc.cityhealth@quezoncity.gov.ph', 'physician' => 'Dr. Paolo S. De Guzman', 'address' => '689 Matapang St., Doña Nicasia Subd.'],
        ['name' => 'Holy Spirit', 'contact' => '09774650063', 'email' => 'holyspirithc.cityhealth@quezoncity.gov.ph', 'physician' => 'Dr. Miguel Gregorio M. Trespeses', 'address' => '373 Sta. Catalina St., Brgy. Holy Spirit'],
        ['name' => 'Lupang Pangako', 'contact' => '09991094962', 'email' => 'lupangpangakohc.cityhealth@quezoncity.gov.ph', 'physician' => 'Dr. Rubelle Anne C. Delos Santos', 'address' => 'Phase I, Lupang Pangako, Brgy. Payatas'],
        ['name' => 'National Government Center Super', 'contact' => '79052053/09452701256', 'email' => 'ngchc.cityhealth@quezoncity.gov.ph', 'physician' => 'Dr. Charise Leah A. Arcenas', 'address' => 'MRB, Phase 1 Pilot Drive, Brgy. Commonwealth'],
        ['name' => 'Payatas A', 'contact' => '7118 4392 / 09650376379', 'email' => 'payatasahealthcenter2021@gmail.com', 'physician' => 'Dr. Anna Marie Katrina A. Boltron', 'address' => 'Ilang-Ilang St., Brgy. Payatas'],
        ['name' => 'Payatas Super', 'contact' => '9156662866', 'email' => '', 'physician' => 'Dr. Roseanne Jan D. Chuca', 'address' => 'Molave St., Diamond Hills St., Brgy. Payatas'],
        ['name' => 'Payatas B', 'contact' => '9690394762', 'email' => 'payatasbhc.cityhealth@quezoncity.gov.ph', 'physician' => 'Dr. Nomer T. Gumiran', 'address' => 'Bulacan St., Brgy. Payatas'],
        ['name' => 'Veterans', 'contact' => '9152656224/73931612', 'email' => 'veteranshc.cityhealth@quezoncity.gov.ph', 'physician' => 'Dr. Samantha Justine C. Dionisio', 'address' => '6 Faustino St., Brgy Holy Spirit'],
    ],
    'District 3' => [
        ['name' => 'District III – Health Office', 'contact' => '9684212677', 'email' => '', 'physician' => 'Dr. Napoleon M. Leonido, MO III, OIC', 'address' => 'New DHO Bldg., beside E. Rodriguez Health Center'],
        ['name' => 'E. Rodriguez', 'contact' => '71171761', 'email' => 'erodriguezhc.cityhealth@quezoncity.gov.ph', 'physician' => 'Dr. Fe S. Florendo', 'address' => '150 Pajo St. Projec 2, Brgy. Quirino 2B'],
        ['name' => 'Ermin Garcia', 'contact' => '70002314', 'email' => 'ermingarciahc.cityhealth@quezoncity.gov.ph', 'physician' => 'Dr. Obermay S. Carabeo', 'address' => '53 Cambridge St., Cubao'],
        ['name' => 'Escopa', 'contact' => '79431484', 'email' => 'escopahc.cityhealth@quezoncity.gov.ph', 'physician' => 'Dr. Paul Bryan M. Sumague', 'address' => 'P. Burgos St., Brgy. Escopa 1'],
        ['name' => 'Libis', 'contact' => '8552 3022', 'email' => 'libishc.cityhealth@quezoncity.gov.ph', 'physician' => 'Dr. Vincent-Lou R. Mendoza', 'address' => 'E. Rodriguez Jr. Avenue cor. L. Pasco St., Brgy Libis'],
        ['name' => 'Murphy Super', 'contact' => '75292027', 'email' => 'murphyshc.cityhealth@quezoncity.gov.ph', 'physician' => 'Dr. Thon Justin G. Filart', 'address' => '37 18th Avenue, Brgy. San Roque'],
        ['name' => 'Old Balara (Main)', 'contact' => '84429251', 'email' => 'oldbalarahc.cityhealth@quezoncity.gov.ph', 'physician' => 'Dr. David Nolan L. Cachola', 'address' => '19 Doña Filomena St., Villa Beatriz, Brgy. Old Balara'],
        ['name' => 'Old Balara (Annex)', 'contact' => '87116325', 'email' => 'oldbalarahc.cityhealth@quezoncity.gov.ph', 'physician' => 'Dr. Aileen Ann M. Orquinaza', 'address' => '99A Tandang Sora Ave, Brgy. Matandang Balara'],
        ['name' => 'Pansol', 'contact' => '70038537', 'email' => 'pansolhc.cityhealth@quezoncity.gov.ph', 'physician' => 'Dr. Charissa L. Alisuag', 'address' => 'Plaza St., Brgy. Pansol'],
        ['name' => 'Project 4', 'contact' => '71490023', 'email' => 'project4hc.cityhealth@quezoncity.gov.ph', 'physician' => 'Dr. Marilin R. Santos', 'address' => 'Kalantiaw st. cor. P. Tuazon, Brgy. Bagumbuhay'],
        ['name' => 'Socorro', 'contact' => '(02) 7117 7234', 'email' => 'socorrohc.cityhealth@quezoncity.gov.ph', 'physician' => 'Dr. Cooper Nikko C. Chavez', 'address' => '139 15th Avenue, Brgy. Socorro'],
    ],
    'District 4' => [
        ['name' => 'District IV – Health Office', 'contact' => '9331932455', 'email' => 'district4.cityhealth@quezoncity.gov.ph', 'physician' => 'Dr. Marizel B. Wong, MO IV', 'address' => 'Tatalon Health Center, #33 Victory Ave., Brgy. Tatalon'],
        ['name' => 'Bernardo', 'contact' => '72949412', 'email' => 'bernardohc.cityhealth@quezoncity.gov.ph', 'physician' => 'Dr. John Christian M. Mirasol', 'address' => '95 Ermin Garcia St., Brgy. Pinagkaisahan'],
        ['name' => 'Cubao', 'contact' => '9454876807', 'email' => 'cubaohc.cityhealth@quezoncity.gov.ph', 'physician' => 'Dr. Karla Marie L. Aguilar', 'address' => '22 Mayor Ignacio Diaz St., Brgy. Kaunlaran'],
        ['name' => 'Galas', 'contact' => '7005 6597', 'email' => 'galashc.cityhealth@quezoncity.gov.ph', 'physician' => 'Dr. Angelica Joel M. Yumol', 'address' => '46 Bayani St. Brgy. San Isidro, Galas'],
        ['name' => 'Gen. Roxas', 'contact' => '', 'email' => 'generalroxashc.cityhealth@quezoncity.gov.ph', 'physician' => 'Dr. Jacqueline T. Ong', 'address' => 'Jasmin St. cor. Madre Silva St., Roxas District'],
        ['name' => 'Kalayaan', 'contact' => '8567 3355', 'email' => 'kalayaanhc.cityhealth@quezoncity.gov.ph', 'physician' => 'Dr. Darlene Pearl L. Superable', 'address' => '91 Guirayan St., Brgy. Doña Imelda'],
        ['name' => 'Kamuning Super', 'contact' => '7092 8594', 'email' => 'kamuninghc.cityhealth@quezoncity.gov.ph', 'physician' => 'Dr. Rochell-Mae L. Detera', 'address' => '2nd Flr., 19 T. Gener St. cor. K-5th St., Brgy. Kamuning'],
        ['name' => 'Krus na Ligas', 'contact' => '9195586190', 'email' => 'krusnaligashc.cityhealth@quezoncity.gov.ph', 'physician' => 'Dr. Cydrick Y. Masangya / Dr. Montana Amir C. Dominguez-Agudelo', 'address' => '89 Lt. J. Francisco, Brgy. Krus na Ligas'],
        ['name' => 'Pinyahan', 'contact' => '7393-1812/7943-9106', 'email' => 'pinyahanhc.cityhealth@quezoncity.gov.ph', 'physician' => 'Dr. Marlon Joselito Roberto F. Molano', 'address' => '37 Malakas St., Brgy. Pinyahan'],
        ['name' => 'San Vicente', 'contact' => '700-58894', 'email' => 'sanvicentehc.cityhealth@quezoncity.gov.ph', 'physician' => 'Dr. Dane Michael S. Calica', 'address' => '#14 Maayusin Ext., Brgy. San Vicente'],
        ['name' => 'Tatalon', 'contact' => '71212955', 'email' => 'tatalonhc.cityhealth@quezoncity.gov.ph', 'physician' => 'Dr. Eyrene V. Amoranto', 'address' => '33 Victory Ave., Brgy. Tatalon'],
    ],
    'District 5' => [
        ['name' => 'District V – Health Office', 'contact' => '0933570172', 'email' => 'district5.cityhealth@quezoncity.gov.ph', 'physician' => 'Dr. Lani C. Buendia, MO IV', 'address' => 'Arsenia J. Maximo (Novaliches) Super HC'],
        ['name' => 'Arsenia de Jesus Maximo Super', 'contact' => '70047692', 'email' => 'ajmaximoshc.cityhealth@quezoncity.gov.ph', 'physician' => 'Dr. Leafar Marie SF. Acorda / Dr. Errolyn Nerisse R. Santos', 'address' => 'Quirino Highway, Brgy. Novaliches Proper'],
        ['name' => 'Bagbag', 'contact' => '71484924', 'email' => 'bagbaghc.cityhealth@quezoncity.gov.ph', 'physician' => 'Dr. Jorja Maria L. Almendrala-Molina', 'address' => '18 Parokya ng Pagkabuhay Road, Brgy. Bagbag'],
        ['name' => 'Capri', 'contact' => '87115952', 'email' => 'caprihealthcenter2023@gmail.com', 'physician' => 'Dr. Charlene G. Deuna', 'address' => 'Narra St. Area 5, Brgy. Capri, Novaliches'],
        ['name' => 'Fairview', 'contact' => '71494641', 'email' => 'fairviewhc.cityhealth@quezoncity.gov.ph', 'physician' => 'Dr. Maria Mae Quinser C. Vargas', 'address' => 'Dahlia Avenue, Brgy. Fairview'],
        ['name' => 'Greater Lagro', 'contact' => '70014728', 'email' => 'greaterlagrohc.cityhealth@quezoncity.gov.ph', 'physician' => 'Dr. Gloria T. Facun', 'address' => 'Blk, 47, Lot 1, Ascension Avenue, Brgy. Greater Lagro'],
        ['name' => 'Gulod', 'contact' => '70029258', 'email' => 'gulodhc.cityhealth@quezoncity.gov.ph', 'physician' => 'Dr. Patricia Anne P. Bonifacio', 'address' => '#47 Villaflor Village, Brgy. Gulod'],
        ['name' => 'Kaligayahan', 'contact' => '71484934 / 09631541440', 'email' => 'kaligayahanhc.cityhealth@quezoncity.gov.ph', 'physician' => 'Dr. Raquel Anne A. Yangkong', 'address' => '58 Kingfisher St., Zabarte Subd.,, Brgy. Kaligayahan'],
        ['name' => 'Maligaya', 'contact' => '864922631', 'email' => '', 'physician' => 'Dr. Ferdinand T. Agustin', 'address' => 'Pechayan St., Maligaya Park Subd., Brgy. Pasong Putik'],
        ['name' => 'Nagkaisang Nayon', 'contact' => '71484964', 'email' => 'nagkaisangnayonhc.cityhealth@quezoncity.gov.ph', 'physician' => 'Dr. Josefa R. Abainza / Dr. Alvie R. Dela Torre (MWF)', 'address' => 'Terio St., FB de Jesus,Sitio Damong Maliit Bgy. Nagkaisang Nayon'],
        ['name' => 'North Fairview', 'contact' => '70037839', 'email' => 'northfairviewhc.cityhealth@quezoncity.gov.ph', 'physician' => 'Dr. Aaron L. Palting', 'address' => 'Avon St., North Fairview Park Subd., Brgy. North Fairview'],
        ['name' => 'San Bartolome', 'contact' => '70929642', 'email' => 'sanbartolomehc.cityhealth@quezoncity.gov.ph', 'physician' => 'Dr. Alfie DT. Navarro (MWF) / Dr. Alvie R. Dela Torre (Th)', 'address' => 'Angela Covered Court, Marcus St. Doña Faustina Subd., Brgy. San Bartolome'],
        ['name' => 'Sta. Lucia Super', 'contact' => '70037431', 'email' => 'staluciashc.cityhealth@quezoncity.gov.ph', 'physician' => 'Dr. Joyce Anne M. Lima', 'address' => 'Sta. Lucia Ave., Brgy. Sta. Lucia'],
    ],
    'District 6' => [
        ['name' => 'District VI – Health Office', 'contact' => '09053025638', 'email' => '', 'physician' => 'Dr. Tina Marie Sanchez-Lucila, MS I, OIC', 'address' => 'Banlat Health Center'],
        ['name' => 'Apolonio Samson', 'contact' => '09687096694', 'email' => 'ASamsonHC.CityHealth@quezoncity.gov.ph', 'physician' => 'Dr. Hanniel Luis C. Aberin', 'address' => '150 Kaingin Road, Brgy. Apolonio Samson, Balintawak'],
        ['name' => 'Baesa', 'contact' => '71484458', 'email' => 'baesahc.cityhealth@quezoncity.gov.ph', 'physician' => 'Dr. Yanis A. Santiago', 'address' => '57 Baesa Road, Brgy. Baesa'],
        ['name' => 'Banlat', 'contact' => '70032412', 'email' => 'banlathc.cityhealth@quezoncity.gov.ph', 'physician' => 'Dr. Margie U. Ibañez', 'address' => '13 Daffodil St. cor. Daisy St., Del Nacia 1 Village, Brgy. Tandang Sora'],
        ['name' => 'Melchora Aquino', 'contact' => '87116016', 'email' => 'maquinohc.cityhealth@quezoncity.gov.ph', 'physician' => 'Dr. Revelation E. Pillien', 'address' => 'Loboc St. Napocor Village, Brgy. Tandang Sora'],
        ['name' => 'Magdaleno H. Pedro', 'contact' => '09254891619', 'email' => 'mhpedrohc.cityhealth@quezoncity.gov.ph', 'physician' => 'Dr. Zaira V. Santos/ Dr. John Eric Sagun', 'address' => '13 J.P. Eugenio St., Philand'],
        ['name' => 'Sangandaan', 'contact' => '71196312', 'email' => 'sangandaanhc.cityhealth@quezoncity.gov.ph', 'physician' => 'Dr. Patricia Aryan A. Nailes', 'address' => 'Premium St., Brgy. Sangandaan'],
        ['name' => 'Sauyo', 'contact' => '09618495092', 'email' => 'sauyohc.cityhealth@quezoncity.gov.ph', 'physician' => 'Dr. Jemellee F. Ricafranca', 'address' => 'Greenville Drive, Brgy. Sauyo'],
        ['name' => 'Tandang Sora', 'contact' => '09600245760', 'email' => 'tandangsorahc.cityhealth@quezoncity.gov.ph', 'physician' => 'Dr. Kristoffer Rundstedt DL. Domingo', 'address' => '506 Quirino Highway, Talipapa People Civic Center, Brgy. Talipapa'],
        ['name' => 'Wenceslao Dela Paz (Culiat)', 'contact' => '71492372', 'email' => 'culiathc.cityhealth@quezoncity.gov.ph', 'physician' => 'Dr. Rica Fatima Charlene E. Arias', 'address' => 'Sta. Felicia St. , San Antonio Homes, Brgy. Culiat'],
    ],
];
